### ISSUE TITLE
status.json raises 500 error

### ISSUE THREAD

**Issue by eltados** [DABSquared/gitlab-plugin#37]
When viewing a merge request on Gitlab, Gitlab makes a request to Jenkins to get the status of the commit, however this raises a NullPointerException.

The request made by Gitlab looks like this:

``https://JENKINS_URL/project/PROJECT_NAME/commits/COMMIT_SHA/status.json?token=TOKEN``

And the NullPointerException traceback is:
``
Caused by: java.lang.NullPointerException
	at com.dabsquared.gitlabjenkins.GitLabWebHook.getBuildBySHA1(GitLabWebHook.java:440)
	at com.dabsquared.gitlabjenkins.GitLabWebHook.generateStatusJSON(GitLabWebHook.java:183)
	at com.dabsquared.gitlabjenkins.GitLabWebHook.getDynamic(GitLabWebHook.java:137)
	at sun.reflect.GeneratedMethodAccessor238.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.MetaClass$12.dispatch(MetaClass.java:389)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)

``

**Comment by k-kawa** [comment]
I got the same error when the Jenkins test job was started by another Jenkins job which starts with Gitlab webhook.
It seems ok for me if the job kicked by Gitlab webhook and the job set as a Gitlab Ci are the same

**Comment by pmalek** [comment]
We're experiencing the same issue but the scenario is a little bit different:
I push a new branch to gitlab, create a merge request and then everything works fine - I get the CI build status on Gitlab merge request page. Then I push another commit to the same branch on Gitlab, build triggers successfully on Jenkins but the status fails, meaning that I have this error:

```
Cannot connect to the CI server. Please check your settings and try again.
```

![image](https://cloud.githubusercontent.com/assets/739996/5855888/6ded3f9a-a23d-11e4-92e1-2c91ec827c1f.png)


This behavior can also be seen while accessing status URLs e.g. `/project/PROJECT_NAME/builds/COMMIT_SHA1/status.json` **BUT** the icon URLs will work work both commits' SHAs ( `/project/PROJECT_NAME/builds/status.png?sha1=COMMIT_SHA1` )

stacktrace that I get on jenkins web page accessing particular broken SHA:

```
Stack trace

javax.servlet.ServletException: java.lang.NullPointerException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:778)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
	at org.kohsuke.stapler.MetaClass$12.dispatch(MetaClass.java:390)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:631)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:225)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:96)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:58)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:99)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:88)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:86)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:46)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:701)
Caused by: java.lang.NullPointerException
	at com.dabsquared.gitlabjenkins.GitLabWebHook.getBuildBySHA1(GitLabWebHook.java:440)
	at com.dabsquared.gitlabjenkins.GitLabWebHook.generateStatusJSON(GitLabWebHook.java:183)
	at com.dabsquared.gitlabjenkins.GitLabWebHook.getDynamic(GitLabWebHook.java:137)
	at sun.reflect.GeneratedMethodAccessor278.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.MetaClass$12.dispatch(MetaClass.java:388)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
	... 62 more
```

**Comment by pmalek** [comment]
The problem seems to be with 

```
at com.dabsquared.gitlabjenkins.GitLabWebHook.getBuildBySHA1(GitLabWebHook.java:440)
```

```java
440:StringParameterValue sourceBranch = (StringParameterValue) params.getParameter("gitlabSourceBranch");
```

not being checked against null but is there a value in this parameter if we are not branching off but commiting/pushing to the same branch (updating branch with new commits for the purposes of MR?)?

**Comment by pmalek** [comment]
Even more tracing for this issue in Jenkins logs (this is what happens on second commit to branch that has an opened MR):

```
Jan 22, 2015 7:23:15 PM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$1 run
XXXXXXXX_gitlab triggered.
Jan 22, 2015 7:23:15 PM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$1 createActions
GitLab Push Request from branch testing_mrs.
Jan 22, 2015 7:23:15 PM WARNING com.dabsquared.gitlabjenkins.GitLabWebHook buildOpenMergeRequests
failed to communicate with gitlab server to determine is this is an update for a merge request: no protocol: /api/v3/projects/22/merge_requests
Jan 22, 2015 7:23:15 PM INFO com.dabsquared.gitlabjenkins.GitLabPushTrigger$1 run
GitLab Push Request detected in XXXXXXXX_gitlab . Triggering  #40
Jan 22, 2015 7:23:22 PM INFO hudson.model.Run execute
XXXXXXXX_gitlab #40 main build action completed: SUCCESS
Jan 22, 2015 7:23:30 PM WARNING com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called.
Jan 22, 2015 7:23:35 PM WARNING com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called.
Jan 22, 2015 7:23:40 PM WARNING com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called.
Jan 22, 2015 7:24:21 PM WARNING com.dabsquared.gitlabjenkins.GitLabWebHook getDynamic
WebHook called.
```

**Comment by bassrock** [comment]
Is this still an issue with the latest version?

**Comment by pmalek** [comment]
I'll let you know when I have the chance to test it (should be up to Friday)

**Comment by bassrock** [comment]
I have not see the 500 error anymore, but I have noticed incorrect statuses. Anyone else?

**Comment by pmalek** [comment]
Ok I have tested it at [3669870](https://github.com/DABSquared/gitlab-plugin/commit/3669870aee4a099e262630976996691093d383f9) and it works as expected.
Both the statuses of build on project pages and on MR pages.

I love this "Add note with build status on merge requests" feature :)

For me the plugin works as expected/needed. Someone can manage the versioning of mvn packaging (`.hpi`).

**Comment by b4oshany** [comment]
Not working for me..... I'm getting the same error.
